apiVersion: v1
kind: Namespace
metadata:
  name: eksappns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksapp
  namespace: eksappns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eksapp
  template:
    metadata:
      labels:
        app: eksapp
    spec:
      containers:
        - name: eksapp
          image: davidayo97/us-mobile-hello:0639995b3f80e7a14abe34515b7dbf3e622e6d61
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eksapp
  namespace: eksappns
spec:
  type: LoadBalancer
  selector:
    app: eksapp
  ports:
    - port: 80
      targetPort: 8080
