name: Monitor ArgoCD and Rollback if Degraded

on:
  schedule:
    - cron: "*/5 * * * *"  # every 10 minutes

jobs:
  rollback-if-degraded:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login to ArgoCD
        run: |
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_PASSWORD --insecure
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}

      - name: Set up Git credentials
        run: |
          git config user.name "davidolufemi"
          git config user.email "davidayodele64@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Check app health and rollback if needed
        run: |
          HEALTH=$(argocd app get eksappargo -o json | jq -r '.status.health.status')
          echo "App health status: $HEALTH"
          if [[ "$HEALTH" == "Degraded" ]]; then
            echo "⚠️ Rolling back to previous commit..."
            git reset --hard HEAD~1
            git push origin HEAD --force
          else
            echo "✅ App is healthy or progressing. No rollback needed."
          fi
